      SUBROUTINE SR.PREP.TESTS (ERR, ID, ANS)
$INCLUDE I_Prologue
      *
      ERR = ""
      ANS = ""
      OPEN "BP.UPL" TO BP.UPL ELSE ERR = "Cannot open BP.UPL"; RETURN
      READ STARTUP FROM BP.UPL, "STARTUP" ELSE ERR = "Cannot find STARTUP in BP.UPL"; RETURN
      EOI = DCOUNT(STARTUP, @FM)
      IF UNASSIGNED(LOG.KEY) OR LOG.KEY="0" THEN
         LOG.KEY = "uHARNESS"
         FOR I = 1 TO EOI
            IF INDEX(STARTUP<I>, "uHARNESS", 1) THEN
               LOG.KEY = STARTUP<I>[INDEX(STARTUP<I>, "uHARNESS", 1), LEN(STARTUP<I>)]
               LOG.KEY = CONVERT(" ", "-", LOG.KEY)
               EXIT
            END
         NEXT I
         MEMORY.VARS(1) = LOG.KEY
         LOG.KEY := @FM
      END
      
      * Make sure the files exists !
      CALL SR.OPEN.CREATE(ERR, "TEST.DATA",  "DYNAMIC", TESTFILE)
      CALL SR.OPEN.CREATE(ERR, "TEST.DATA1", "DYNAMIC", TESTFILE1)
      CALL SR.OPEN.CREATE(ERR, "TEST.DATA2", "DYNAMIC", TESTFILE2)
      CALL SR.OPEN.CREATE(ERR, "UF0001",     "DYNAMIC", JUNKFILE)
      
      IF ERR# "" THEN ANS=ERR; RETURN
      
      IF ID = "" THEN
         CMD = "CLEAR-FILE TEST.DATA"
         EXECUTE CMD CAPTURING JUNK
         LOG.MSG = "CLEARed TEST.DATA"
         IF INF.LOGGING THEN CALL uLOGGER(0, LOG.KEY:LOG.MSG)
         
         CMD = "CLEAR-FILE TEST.DATA1"
         EXECUTE CMD CAPTURING JUNK
         LOG.MSG = "CLEARed TEST.DATA1"
         IF INF.LOGGING THEN CALL uLOGGER(0, LOG.KEY:LOG.MSG)
         
         CMD = "CLEAR-FILE TEST.DATA2"
         EXECUTE CMD CAPTURING JUNK
         LOG.MSG = "CLEARed TEST.DATA2"
         IF INF.LOGGING THEN CALL uLOGGER(0, LOG.KEY:LOG.MSG)
      END ELSE
         DELETE TESTFILE, ID
         LOG.MSG = "DELETEd record ":ID" from TEST.DATA"
         IF INF.LOGGING THEN CALL uLOGGER(0, LOG.KEY:LOG.MSG)
         DELETE TESTFILE1, ID
         LOG.MSG = "DELETEd record ":ID" from TEST.DATA1"
         IF INF.LOGGING THEN CALL uLOGGER(0, LOG.KEY:LOG.MSG)
         DELETE TESTFILE2, ID
         LOG.MSG = "DELETEd record ":ID" from TEST.DATA2"
         IF INF.LOGGING THEN CALL uLOGGER(0, LOG.KEY:LOG.MSG)
      END
$IFDEF isRT
      EXE = "DELETE MD CLR.TESTFILES"
$ELSE
      EXE = "DELETE VOC CLR.TESTFILES"
$ENDIF
      EXECUTE EXE CAPTURING JUNK
      LOG.MSG = EXE:"  response: ":JUNK
      IF INF.LOGGING THEN CALL uLOGGER(0, LOG.KEY:LOG.MSG)
      
      CALL SR.FILE.CLOSE (ERR, "TEST.DATA")
      IF ERR# "" THEN ANS=ERR; RETURN
      CALL SR.FILE.CLOSE (ERR, "TEST.DATA1")
      IF ERR# "" THEN ANS=ERR; RETURN
      CALL SR.FILE.CLOSE (ERR, "TEST.DATA2")
      IF ERR# "" THEN ANS=ERR; RETURN
      EXECUTE "DELETE VOC CLR.TESTFILES" CAPTURING JUNK
      ANS = "PASS - cleared TEST.DATA"
      RETURN
   END
