ERR = ""
OPEN "LAY" TO LAY ELSE STOP "Cannot open LAY. You need to u2-set/view it"
SELECT LAY TO LAYIDS
LOOP WHILE READNEXT LAYID FROM LAYIDS DO
    READ LAYITEM FROM LAY,LAYID ELSE STOP
    PRINT "---------"
    PRINT LAYID
    PRINT "---------"
    EOF = DCOUNT(LAYITEM, @FM)
    FOR I = 1 TO EOF
       LAYLINE = LAYITEM<I>
       PRINT LAYLINE
    NEXT I
REPEAT