package com.unilibre.commons;
/*Copyright UniLibre on 2015. ALL RIGHTS RESERVED */

// Splice does NOT differentiate on DB.
// Schema is the 'logical' DB
// TABLE NAME is [schema + "_" + table]
// ---------------------------------------------

public class uSpliceCommons {

    public static String CreateTable(String DB, String SCH, String TBL, String[] tCols) {
        String cmd = "";
        String idxName = TBL + "_idx";
        if (SCH.equals(NamedCommon.rawSC)) idxName = TBL + "_ridx";
        String keytype = " varchar(150) not null";
        String maxtype = " long varchar ";
        String dbFocus = DB + "." + SCH + "_" + TBL; // e.g. RFUEL.RAW_CLIENT
        String tmpStr = "";
        tmpStr += "CREATE TABLE " + dbFocus + " ( ";
        tmpStr += "SeqnID BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY, ";
        int x = 9;
        NamedCommon.pKeys = "";
        for (int xx = 0; xx < tCols.length; xx++) {
            if (tCols[xx].length() > 1) {
                /* --------------------------------------------------------- */
                if (tCols[xx].startsWith("*")) {
                    tCols[xx] = tCols[xx].substring(1, (tCols[xx].length()));
                    tmpStr = tmpStr + "   " + tCols[xx] + maxtype + ", ";
                } else {
                    if (tCols[xx].startsWith("-") || tCols[xx].contains("ID")) {
                        tCols[xx] = tCols[xx].substring(1, (tCols[xx].length()));
                        tmpStr = tmpStr + "   " + tCols[xx] + keytype + ", ";
                    } else {
                        // tmpStr = tmpStr + "   " + tCols[xx] + sqltype + ", ";
                        tmpStr = tmpStr + "   " + tCols[xx] + maxtype + ", ";
                    }
                }
                if (tCols[xx].contains("ID")) {
                    NamedCommon.pKeys = NamedCommon.pKeys + tCols[xx] + ",";
                }
                /* --------------------------------------------------------- */
                x++;
            }
        }
        while (!tmpStr.endsWith(",")) {
            tmpStr = tmpStr.substring(0, (tmpStr.length() - 1));
        }
        tmpStr = tmpStr.substring(0, (tmpStr.length() - 1));
        tmpStr = tmpStr + " )";
        if (!NamedCommon.pKeys.equals("")) {
            NamedCommon.pKeys = NamedCommon.pKeys.substring(0, (NamedCommon.pKeys.length() - 1));
            NamedCommon.pKeys = NamedCommon.pKeys + ",";
        }
        tmpStr = tmpStr + "\n";
        tmpStr = tmpStr + "CREATE UNIQUE INDEX " + idxName + " on " + dbFocus + " (";
        if (!NamedCommon.pKeys.equals("")) {
            tmpStr = tmpStr + NamedCommon.pKeys + "MD5)";
        } else {
            tmpStr = tmpStr + "SeqnID,ProcNum,MD5)";
        }
        // tmpStr += "\ncommit";
        cmd = tmpStr;
        return cmd;
    }

    public static String CreateIndex(String DB, String SCH, String TBL, String[] tCols) {
        return "";
    }

    public static String DropTable(String DB, String SCH, String TBL) {
        String dbFocus = DB + "." + SCH + "_" + TBL; // e.g. RFUEL.RAW_CLIENT
        String cmd = "DROP TABLE IF EXISTS " + dbFocus;
        return cmd;
    }

    public static String AlterTable(String DB, String SCH, String TBL) {
        String cmd = "";

        return cmd;
    }

    public static String BulkImport(String fname, String Path2Data) {
        // fname:: [DB].[SCH].[TBL]
        fname = fname.replaceAll("\\[", "");
        fname = fname.replaceAll("\\]", "");
        Path2Data = "/tmp/" + fname;
        String Komma = NamedCommon.Komma;
        String ColList = "null";
        String ColDelm = "'|'";
        String ChrDelm = "null";
        String TSfmt = "null";
        String DTfmt = "null";
        String TMfmt = "null";
        String BadRec = "0";            // may want to parameterise.
        String BadDir = "null";
        String OneLine = "true";
        String ChrSet = "null";
        String DB = "";
        String SCH = "";
        String TBL = "";
        // usage :: [RFUEL]_[STG]_[CLIENT]
        //    to :: RFUEL.STR_CLIENT
        DB = "'" + uCommons.FieldOf(fname, "_", 1) + "'";
        SCH = uCommons.FieldOf(fname, "_", 2);
        TBL = uCommons.FieldOf(fname, "_", 3);
        TBL = "'" + SCH + "_" + TBL + "'";
        Path2Data = "'" + Path2Data + "'";
        String cmd = "call SYSCS_UTIL.IMPORT_DATA (" +
                DB + "," +
                TBL + "," +
                ColList + "," +
                Path2Data + "," +        // '/import/xyz.dat'
                ColDelm + "," +
                ChrDelm + "," +
                TSfmt + "," +
                DTfmt + "," +
                TMfmt + "," +
                BadRec + "," +
                BadDir + // ","+           // '/bad'
//                OneLine + ","+
//                ChrSet +
                ")";
        return cmd;
    }

    public static void TouchControl() {
        /*
        String DB = NamedCommon.SqlDatabase;
        String SCH = "CTL";
        String TBL = "RUNCONTROL";
        String cmd = "";
        ArrayList<String> cmdList = new ArrayList<String>();
        cmdList.clear();
        cmd += "CREATE TABLE " + DB + "." + SCH + "_" + TBL + " (";
        cmd += "SeqnID BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY, ";
        cmd += "BatchID varchar(150), ";
        cmd += "u2File varchar(150), ";
        cmd += "uID varchar(150), ";
        cmd += "Status INT NOT NULL DEFAULT 0 )";
        cmdList.clear();
        cmdList.add(cmd);
        SqlCommands.ExecuteSQL(cmdList);
        if (NamedCommon.ZERROR) return;
        */
    }

}
